### PR TITLE
Migrate code straight from API ZEN-1162

### PR DESCRIPTION
**Pull request by tehpsalmist**

### CODE REVIEW

**Comment by AParks** [comment]
is there a separate update for legacy wrapper readme to include this new path?

**Comment by tehpsalmist** [comment]
what new path?

**Review by alexweber — COMMENTED** [review]
seems good deferring to others with more familiarity with this repo

**Comment by JoeBello** [comment]
Great stuff. Looks good. One thing I wanted to mention; if I try to pull a plugin from the Zengine API, but I don't pass a token from the account that owns the plugin, there's nothing yelling at me to use a token from the owning account - I just end up with "undefined" in my plugin files.

**Comment by tehpsalmist** [comment]
Thanks Joe!

**Review by wizehive-chrismanjoine — APPROVED** [review]
This works awesome Ben. 

Often times we have plugins that don't have repos and this makes it super easy to download them and migrate. It works as expected.

**Pull request merged**
